language: python

python:
- "3.6"

install: 
  - pip install -r requirements.txt
  - pip install coverage
script: 
  - coverage run --source=app.py -m py.test && coverage report

after_success:
  - coveralls